// Seed HQ master data — a representative spread of pharma-division HQs
// across the gazetteer's coverage, enough to exercise all 4 classification
// tiers (GREEN/YELLOW/ORANGE/RED) once run against the FO roster in
// people.mock.ts. Mirrors hq-serviceability.js's own seeded HQ_MASTER.
// TODO: entirely mock/frontend-only — no backend endpoints exist yet.

import type { HqRecord } from '@/features/hq/hq.types'

export const SEED_HQS: HqRecord[] = [
  { id: 'hq-001', company: 'Abbott', division: 'Nutrition', hqCode: 'ABT-MUM-01', hqName: 'Mumbai Central', state: 'MH', district: 'Mumbai', city: 'Mumbai', pincode: '400001', priority: 'HIGH', businessPotential: 'Platinum', requiredDevice: 'BP Monitor', campsPerMonth: 12, createdAt: '2026-01-05T09:00:00.000Z', source: 'seed' },
  { id: 'hq-002', company: 'Abbott', division: 'Nutrition', hqCode: 'ABT-PUN-01', hqName: 'Pune Camp', state: 'MH', district: 'Pune', city: 'Pune', pincode: '411001', priority: 'HIGH', businessPotential: 'Gold', requiredDevice: 'ECG', campsPerMonth: 8, createdAt: '2026-01-05T09:00:00.000Z', source: 'seed' },
  { id: 'hq-003', company: 'Cipla', division: 'Cardiac', hqCode: 'CIP-DEL-01', hqName: 'Delhi HQ', state: 'DL', district: 'New Delhi', city: 'Delhi', pincode: '110001', priority: 'HIGH', businessPotential: 'Platinum', requiredDevice: 'ECG', campsPerMonth: 15, createdAt: '2026-01-06T09:00:00.000Z', source: 'seed' },
  { id: 'hq-004', company: 'Cipla', division: 'Cardiac', hqCode: 'CIP-GGN-01', hqName: 'Gurgaon Sector 44', state: 'HR', district: 'Gurgaon', city: 'Gurgaon', pincode: '122001', priority: 'MED', businessPotential: 'Gold', requiredDevice: 'ECG', campsPerMonth: 6, createdAt: '2026-01-06T09:00:00.000Z', source: 'seed' },
  { id: 'hq-005', company: 'Sun Pharma', division: 'Diabetes', hqCode: 'SUN-BLR-01', hqName: 'Bangalore Whitefield', state: 'KA', district: 'Bangalore', city: 'Bangalore', pincode: '560066', priority: 'HIGH', businessPotential: 'Platinum', requiredDevice: 'Glucometer', campsPerMonth: 10, createdAt: '2026-01-07T09:00:00.000Z', source: 'seed' },
  { id: 'hq-006', company: 'Sun Pharma', division: 'Diabetes', hqCode: 'SUN-MYS-01', hqName: 'Mysuru', state: 'KA', district: 'Mysuru', city: 'Mysore', pincode: '570001', priority: 'MED', businessPotential: 'Silver', requiredDevice: 'Glucometer', campsPerMonth: 4, createdAt: '2026-01-07T09:00:00.000Z', source: 'seed' },
  { id: 'hq-007', company: 'Lupin', division: 'Respiratory', hqCode: 'LUP-CHN-01', hqName: 'Chennai T Nagar', state: 'TN', district: 'Chennai', city: 'Chennai', pincode: '600017', priority: 'HIGH', businessPotential: 'Gold', requiredDevice: 'SpO2', campsPerMonth: 9, createdAt: '2026-01-08T09:00:00.000Z', source: 'seed' },
  { id: 'hq-008', company: 'Lupin', division: 'Respiratory', hqCode: 'LUP-CBE-01', hqName: 'Coimbatore', state: 'TN', district: 'Coimbatore', city: 'Coimbatore', pincode: '641001', priority: 'LOW', businessPotential: 'Bronze', requiredDevice: 'SpO2', campsPerMonth: 3, createdAt: '2026-01-08T09:00:00.000Z', source: 'seed' },
  { id: 'hq-009', company: 'Dr Reddy\'s', division: 'General Wellness', hqCode: 'DRL-HYD-01', hqName: 'Hyderabad Banjara Hills', state: 'TG', district: 'Hyderabad', city: 'Hyderabad', pincode: '500034', priority: 'HIGH', businessPotential: 'Platinum', requiredDevice: 'BMI Scale', campsPerMonth: 11, createdAt: '2026-01-09T09:00:00.000Z', source: 'seed' },
  { id: 'hq-010', company: 'Dr Reddy\'s', division: 'General Wellness', hqCode: 'DRL-VZG-01', hqName: 'Visakhapatnam', state: 'AP', district: 'Visakhapatnam', city: 'Visakhapatnam', pincode: '530001', priority: 'MED', businessPotential: 'Silver', requiredDevice: 'BMI Scale', campsPerMonth: 4, createdAt: '2026-01-09T09:00:00.000Z', source: 'seed' },
  { id: 'hq-011', company: 'Mankind', division: 'Cardiac', hqCode: 'MKD-KOL-01', hqName: 'Kolkata Salt Lake', state: 'WB', district: 'Kolkata', city: 'Kolkata', pincode: '700064', priority: 'HIGH', businessPotential: 'Gold', requiredDevice: 'ECG', campsPerMonth: 7, createdAt: '2026-01-10T09:00:00.000Z', source: 'seed' },
  { id: 'hq-012', company: 'Mankind', division: 'Cardiac', hqCode: 'MKD-SIL-01', hqName: 'Siliguri', state: 'WB', district: 'Siliguri', city: 'Siliguri', pincode: '734001', priority: 'LOW', businessPotential: 'Bronze', requiredDevice: 'ECG', campsPerMonth: 2, createdAt: '2026-01-10T09:00:00.000Z', source: 'seed' },
  { id: 'hq-013', company: 'Zydus', division: 'Diabetes', hqCode: 'ZYD-AMD-01', hqName: 'Ahmedabad Navrangpura', state: 'GJ', district: 'Ahmedabad', city: 'Ahmedabad', pincode: '380009', priority: 'HIGH', businessPotential: 'Platinum', requiredDevice: 'Glucometer', campsPerMonth: 13, createdAt: '2026-01-11T09:00:00.000Z', source: 'seed' },
  { id: 'hq-014', company: 'Zydus', division: 'Diabetes', hqCode: 'ZYD-RAJ-01', hqName: 'Rajkot', state: 'GJ', district: 'Rajkot', city: 'Rajkot', pincode: '360001', priority: 'MED', businessPotential: 'Silver', requiredDevice: 'Glucometer', campsPerMonth: 3, createdAt: '2026-01-11T09:00:00.000Z', source: 'seed' },
  { id: 'hq-015', company: 'Torrent', division: 'General Wellness', hqCode: 'TOR-JAI-01', hqName: 'Jaipur C-Scheme', state: 'RJ', district: 'Jaipur', city: 'Jaipur', pincode: '302001', priority: 'MED', businessPotential: 'Gold', requiredDevice: 'BMI Scale', campsPerMonth: 5, createdAt: '2026-01-12T09:00:00.000Z', source: 'seed' },
  { id: 'hq-016', company: 'Torrent', division: 'General Wellness', hqCode: 'TOR-UDR-01', hqName: 'Udaipur', state: 'RJ', district: 'Udaipur', city: 'Udaipur', pincode: '313001', priority: 'LOW', businessPotential: 'Bronze', requiredDevice: 'BMI Scale', campsPerMonth: 1, createdAt: '2026-01-12T09:00:00.000Z', source: 'seed' },
  { id: 'hq-017', company: 'Alkem', division: 'Respiratory', hqCode: 'ALK-LKO-01', hqName: 'Lucknow Gomti Nagar', state: 'UP', district: 'Lucknow', city: 'Lucknow', pincode: '226010', priority: 'HIGH', businessPotential: 'Gold', requiredDevice: 'SpO2', campsPerMonth: 8, createdAt: '2026-01-13T09:00:00.000Z', source: 'seed' },
  { id: 'hq-018', company: 'Alkem', division: 'Respiratory', hqCode: 'ALK-VNS-01', hqName: 'Varanasi', state: 'UP', district: 'Varanasi', city: 'Varanasi', pincode: '221001', priority: 'LOW', businessPotential: 'Bronze', requiredDevice: 'SpO2', campsPerMonth: 2, createdAt: '2026-01-13T09:00:00.000Z', source: 'seed' },
  { id: 'hq-019', company: 'Biocon', division: 'Diabetes', hqCode: 'BIO-PAT-01', hqName: 'Patna Boring Road', state: 'BR', district: 'Patna', city: 'Patna', pincode: '800001', priority: 'MED', businessPotential: 'Silver', requiredDevice: 'Glucometer', campsPerMonth: 4, createdAt: '2026-01-14T09:00:00.000Z', source: 'seed' },
  { id: 'hq-020', company: 'Biocon', division: 'Diabetes', hqCode: 'BIO-GAY-01', hqName: 'Gaya', state: 'BR', district: 'Gaya', city: 'Gaya', pincode: '823001', priority: 'LOW', businessPotential: 'Bronze', requiredDevice: 'Glucometer', campsPerMonth: 1, createdAt: '2026-01-14T09:00:00.000Z', source: 'seed' },
  { id: 'hq-021', company: 'Intas', division: 'Cardiac', hqCode: 'INT-BHU-01', hqName: 'Bhubaneswar', state: 'OR', district: 'Bhubaneswar', city: 'Bhubaneswar', pincode: '751001', priority: 'MED', businessPotential: 'Silver', requiredDevice: 'ECG', campsPerMonth: 3, createdAt: '2026-01-15T09:00:00.000Z', source: 'seed' },
  { id: 'hq-022', company: 'Intas', division: 'Cardiac', hqCode: 'INT-RAN-01', hqName: 'Ranchi', state: 'JH', district: 'Ranchi', city: 'Ranchi', pincode: '834001', priority: 'LOW', businessPotential: 'Bronze', requiredDevice: 'ECG', campsPerMonth: 2, createdAt: '2026-01-15T09:00:00.000Z', source: 'seed' },
  { id: 'hq-023', company: 'Glenmark', division: 'General Wellness', hqCode: 'GLN-GUW-01', hqName: 'Guwahati', state: 'AS', district: 'Guwahati', city: 'Guwahati', pincode: '781001', priority: 'MED', businessPotential: 'Gold', requiredDevice: 'BMI Scale', campsPerMonth: 5, createdAt: '2026-01-16T09:00:00.000Z', source: 'seed' },
  { id: 'hq-024', company: 'Glenmark', division: 'General Wellness', hqCode: 'GLN-SHL-01', hqName: 'Shillong', state: 'ML', district: 'Shillong', city: 'Shillong', pincode: '793001', priority: 'LOW', businessPotential: 'Bronze', requiredDevice: 'BMI Scale', campsPerMonth: 1, createdAt: '2026-01-16T09:00:00.000Z', source: 'seed' },
  { id: 'hq-025', company: 'Abbott', division: 'Nutrition', hqCode: 'ABT-NGP-01', hqName: 'Nagpur', state: 'MH', district: 'Nagpur', city: 'Nagpur', pincode: '440001', priority: 'MED', businessPotential: 'Silver', requiredDevice: 'BP Monitor', campsPerMonth: 4, createdAt: '2026-01-17T09:00:00.000Z', source: 'seed' },
  { id: 'hq-026', company: 'Cipla', division: 'Cardiac', hqCode: 'CIP-CHD-01', hqName: 'Chandigarh Sector 17', state: 'CH', district: 'Chandigarh', city: 'Chandigarh', pincode: '160017', priority: 'MED', businessPotential: 'Gold', requiredDevice: 'ECG', campsPerMonth: 6, createdAt: '2026-01-18T09:00:00.000Z', source: 'seed' },
  { id: 'hq-027', company: 'Sun Pharma', division: 'Diabetes', hqCode: 'SUN-KOC-01', hqName: 'Kochi Marine Drive', state: 'KL', district: 'Kochi', city: 'Kochi', pincode: '682031', priority: 'HIGH', businessPotential: 'Gold', requiredDevice: 'Glucometer', campsPerMonth: 7, createdAt: '2026-01-19T09:00:00.000Z', source: 'seed' },
  { id: 'hq-028', company: 'Mankind', division: 'Cardiac', hqCode: 'MKD-BHO-01', hqName: 'Bhopal MP Nagar', state: 'MP', district: 'Bhopal', city: 'Bhopal', pincode: '462011', priority: 'MED', businessPotential: 'Silver', requiredDevice: 'ECG', campsPerMonth: 4, createdAt: '2026-01-20T09:00:00.000Z', source: 'seed' },
  { id: 'hq-029', company: 'Zydus', division: 'Diabetes', hqCode: 'ZYD-IND-01', hqName: 'Indore Vijay Nagar', state: 'MP', district: 'Indore', city: 'Indore', pincode: '452010', priority: 'HIGH', businessPotential: 'Gold', requiredDevice: 'Glucometer', campsPerMonth: 8, createdAt: '2026-01-21T09:00:00.000Z', source: 'seed' },
  { id: 'hq-030', company: 'Torrent', division: 'General Wellness', hqCode: 'TOR-SRI-01', hqName: 'Srinagar', state: 'JK', district: 'Srinagar', city: 'Srinagar', pincode: '190001', priority: 'LOW', businessPotential: 'Bronze', requiredDevice: 'BMI Scale', campsPerMonth: 1, createdAt: '2026-01-22T09:00:00.000Z', source: 'seed' },
]
