import type { Meeting, MeetingOwner } from '@/types/meeting.types'

// TODO: entirely mock — no backend endpoints exist for sales meetings yet.
// Dates are relative to "today" via dPlus() so the calendar always has data.

export const OWNERS: MeetingOwner[] = [
  { id: 'rm', name: 'Riya Mehta', tone: 'teal' },
  { id: 'ak', name: 'Arjun Kapoor', tone: 'brand' },
  { id: 'sn', name: 'Sneha Nair', tone: 'violet' },
  { id: 'vp', name: 'Vikram Pillai', tone: 'emerald' },
]

export const PHARMA_COMPANIES: { id: string; name: string }[] = [
  { id: 'cli-sun', name: 'Sun Pharma' },
  { id: 'cli-cipla', name: 'Cipla' },
  { id: 'cli-drreddys', name: "Dr Reddy's" },
  { id: 'cli-abbott', name: 'Abbott India' },
  { id: 'cli-lupin', name: 'Lupin' },
  { id: 'cli-zydus', name: 'Zydus' },
  { id: 'cli-glenmark', name: 'Glenmark' },
  { id: 'cli-fortis', name: 'Fortis Healthcare' },
]

function dPlus(days: number, hour: number, min = 0): string {
  const d = new Date()
  d.setDate(d.getDate() + days)
  d.setHours(hour, min, 0, 0)
  return d.toISOString()
}

export const MEETINGS: Meeting[] = [
  {
    id: 'mt-001',
    meetingNo: 'MTG-0001',
    ownerId: 'rm',
    ownerName: 'Riya Mehta',
    ownerTone: 'teal',
    type: 'NEW',
    status: 'PLANNED',
    pharmaCompanyId: 'cli-sun',
    pharmaName: 'Sun Pharma',
    divisionName: 'Cardio Care',
    contactName: 'Rakesh Jain',
    contactRole: 'Zonal Manager',
    city: 'Mumbai',
    location: 'Sun House, Goregaon',
    modeOfMeeting: 'IN_PERSON',
    startAt: dPlus(0, 10, 30),
    endAt: dPlus(0, 11, 30),
    agendaPublic: 'Intro pitch — screening camp portfolio for cardio brands',
    agendaPrivate: 'Zonal head open to a Q3 pilot; anchor on Mumbai coverage strength',
    nextSteps: 'Share rate card after the meeting',
    createdAt: dPlus(-6, 9),
    updatedAt: dPlus(-1, 17),
  },
  {
    id: 'mt-002',
    meetingNo: 'MTG-0002',
    ownerId: 'rm',
    ownerName: 'Riya Mehta',
    ownerTone: 'teal',
    type: 'FOLLOWUP',
    status: 'DONE',
    pharmaCompanyId: 'cli-cipla',
    pharmaName: 'Cipla',
    divisionName: 'Respiratory',
    contactName: 'Meera Shah',
    contactRole: 'Brand Manager',
    city: 'Mumbai',
    modeOfMeeting: 'VIRTUAL',
    startAt: dPlus(-1, 15),
    endAt: dPlus(-1, 16),
    agendaPublic: 'Follow-up on the spirometry camp proposal',
    nextSteps: 'Send MSA draft with per-camp reporting SLAs',
    linkedLeadId: 'L-2415',
    momText:
      'Walked through revised commercials. Client wants per-camp reporting SLAs added to the MSA; procurement to be looped in next week.',
    momSubmittedAt: dPlus(-1, 16, 40),
    createdAt: dPlus(-9, 10),
    updatedAt: dPlus(-1, 16, 40),
  },
  {
    id: 'mt-003',
    meetingNo: 'MTG-0003',
    ownerId: 'rm',
    ownerName: 'Riya Mehta',
    ownerTone: 'teal',
    type: 'PAYMENT',
    status: 'PLANNED',
    pharmaCompanyId: 'cli-abbott',
    pharmaName: 'Abbott India',
    divisionName: 'Diabetes Care',
    contactName: 'Suresh Iyer',
    contactRole: 'Accounts Head',
    city: 'Mumbai',
    location: 'Abbott House, BKC',
    modeOfMeeting: 'IN_PERSON',
    startAt: dPlus(-3, 11),
    endAt: dPlus(-3, 11, 45),
    agendaPublic: 'Collect pending Q1 invoices — PRJ-437',
    // No MOM submitted — the 24-working-hour sweep will auto-block this one
    createdAt: dPlus(-8, 12),
    updatedAt: dPlus(-3, 9),
  },
  {
    id: 'mt-004',
    meetingNo: 'MTG-0004',
    ownerId: 'vp',
    ownerName: 'Vikram Pillai',
    ownerTone: 'emerald',
    type: 'NEW',
    status: 'DONE',
    pharmaCompanyId: 'cli-abbott',
    pharmaName: 'Abbott India',
    divisionName: 'Nutrition',
    contactName: 'Anita Desai',
    contactRole: 'Marketing Head',
    city: 'Delhi',
    modeOfMeeting: 'IN_PERSON',
    startAt: dPlus(-2, 12),
    endAt: dPlus(-2, 13),
    agendaPublic: 'Nutrition camp concept for the pediatric range',
    momText: 'Strong interest in a 20-camp pilot across NCR. Budget owner aligned; brief moving to procurement.',
    momSubmittedAt: dPlus(-2, 14, 30),
    outcome: 'CONVERTED_LEAD',
    outcomeReason: 'Pilot budget approved verbally in the meeting',
    createdAt: dPlus(-10, 9),
    updatedAt: dPlus(-2, 14, 30),
  },
  {
    id: 'mt-005',
    meetingNo: 'MTG-0005',
    ownerId: 'rm',
    ownerName: 'Riya Mehta',
    ownerTone: 'teal',
    type: 'FOLLOWUP',
    status: 'RELEASED',
    pharmaCompanyId: 'cli-drreddys',
    pharmaName: "Dr Reddy's",
    divisionName: 'Oncology',
    contactName: 'Kiran Kumar',
    contactRole: 'Cluster Head',
    city: 'Hyderabad',
    modeOfMeeting: 'IN_PERSON',
    startAt: dPlus(-5, 10),
    endAt: dPlus(-5, 11),
    agendaPublic: 'Review pilot camp feedback and expansion plan',
    linkedLeadId: 'L-2398',
    blockedAt: dPlus(-3, 12),
    blockReason: 'Late MOM',
    releasedBy: 'Arjun Kapoor',
    releasedAt: dPlus(-2, 9, 30),
    releaseReason: 'Rep was on approved leave; client meeting rescheduled',
    createdAt: dPlus(-12, 11),
    updatedAt: dPlus(-2, 9, 30),
  },
  {
    id: 'mt-006',
    meetingNo: 'MTG-0006',
    ownerId: 'ak',
    ownerName: 'Arjun Kapoor',
    ownerTone: 'brand',
    type: 'NEW',
    status: 'PLANNED',
    pharmaCompanyId: 'cli-lupin',
    pharmaName: 'Lupin',
    contactName: 'Devika Rao',
    contactRole: 'Brand Manager',
    city: 'Pune',
    modeOfMeeting: 'IN_PERSON',
    startAt: dPlus(0, 14),
    endAt: dPlus(0, 15),
    agendaPublic: 'Intro — screening camps for the cardiology franchise',
    createdAt: dPlus(-4, 10),
    updatedAt: dPlus(-4, 10),
  },
  {
    id: 'mt-007',
    meetingNo: 'MTG-0007',
    ownerId: 'sn',
    ownerName: 'Sneha Nair',
    ownerTone: 'violet',
    type: 'SPOT',
    status: 'PLANNED',
    pharmaCompanyId: 'cli-zydus',
    pharmaName: 'Zydus',
    contactName: 'Harsh Patel',
    contactRole: 'ASM',
    city: 'Ahmedabad',
    modeOfMeeting: 'VIRTUAL',
    startAt: dPlus(1, 11),
    endAt: dPlus(1, 11, 30),
    agendaPublic: 'Spot sync — device availability for next month',
    createdAt: dPlus(-1, 18),
    updatedAt: dPlus(-1, 18),
  },
  {
    id: 'mt-008',
    meetingNo: 'MTG-0008',
    ownerId: 'vp',
    ownerName: 'Vikram Pillai',
    ownerTone: 'emerald',
    type: 'PAYMENT',
    status: 'PLANNED',
    pharmaCompanyId: 'cli-glenmark',
    pharmaName: 'Glenmark',
    contactName: 'Nisha Menon',
    contactRole: 'Finance Controller',
    city: 'Mumbai',
    modeOfMeeting: 'IN_PERSON',
    startAt: dPlus(2, 16),
    endAt: dPlus(2, 17),
    agendaPublic: 'Reconcile outstanding derma camp invoices',
    createdAt: dPlus(-2, 13),
    updatedAt: dPlus(-2, 13),
  },
]
